apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: {{ .Values.Agent.ComponentName }}
    app: {{template "name" .}}
spec:
  replicas: {{ .Values.Agent.Replicas }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        component: {{.Values.Agent.ComponentName}}
        app: {{template "name" .}}
    spec:
      nodeSelector:
        role: master
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Exists
          effect: NoSchedule
      containers:
      - name: {{ template "fullname" . }}
        image: "{{.Values.Agent.Image}}:{{.Values.Agent.ImageTag}}"
        imagePullPolicy: "{{.Values.Agent.ImagePullPolicy}}"
        env:
        - name: AGENT_INTERVAL
          value: {{ .Values.Agent.Interval | quote }}
        - name: API_KEY
          value: {{ .Values.Agent.ApiKey }}
        - name: DNS_ZONE_IDS
          value: "{{ .Values.Agent.DnsZoneIds }}"
        - name: "API_ENDPOINT"
          value: "{{ .Values.Agent.ApiEndpoint }}"
        - name: "KOPS_STATE_STORE"
          value: "{{ .Values.Agent.KopsStateStore }}"
        - name: "AWS_ACCESS_KEY_ID"
          value: "{{ .Values.Agent.AwsAccessKey }}"
        - name: "AWS_SECRET_ACCESS_KEY"
          value: "{{ .Values.Agent.AwsSecretKey }}"
